version: 2

updates:
  # GitHub Actions (Own & Template)
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "template/*/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      github-actions:
        patterns:
          - "*"
  # npm (Own & Template Frontend/Infrastructure)
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "template/*/frontend/"
      - "template/*/infrastructure/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      minor-patch-upgrades:
        # Make sure you add all more specific patterns of groups tackling major updates
        patterns:
          - "*"
          - "*vite*"
          - "*svelte*"
          - "*aws*"
        update-types:
          - "minor"
          - "patch"
      vite-major-upgrades:
        patterns:
          - "*vite*" # covers also vitest, but major updates on same day are rare
        update-types:
          - "major"
      svelte-major-upgrades:
        patterns:
          - "*svelte*"
        update-types:
          - "major"
      aws-major-upgrades:
        patterns:
          - "*aws*"
        update-types:
          - "major"

  # Template's Backend
  - package-ecosystem: "cargo"
    directories:
      - "template/*/backend/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      minor-patch-upgrades:
        # Make sure you add all more specific patterns of groups tackling major updates
        patterns:
          - "*"
          - "*aws*"
          - "lambda*"
        update-types:
          - "minor"
          - "patch"
      aws-major-upgrades:
        patterns:
          - "*aws*"
          - "lambda*"
        update-types:
          - "major"
