version: 2
updates:
  # GitHub Actions (Own & Template)
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "template/*/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns:
          - "*"

  # npm (Own & Template Frontend/Infrastructure)
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "template/*/frontend/"
      - "template/*/infrastructure/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      aws-major:
        patterns:
          - "aws-cdk"
          - "aws-cdk-lib"
          - "cargo-lambda-cdk"
          - "@aws-cdk/*"
          - "@aws-sdk/*"
        update-types:
          - "major"
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Template's Backend
  - package-ecosystem: "cargo"
    directories:
      - "template/*/backend/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      aws-major:
        patterns:
          - "aws-config"
          - "aws-credential-types"
          - "aws-sdk-*"
          - "aws_lambda_events"
          - "lambda_http"
          - "lambda_runtime"
        update-types:
          - "major"
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

