version: 2

updates:
  # GitHub Actions (Own & Template)
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "template/*/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      github-actions:
        patterns: ["*"]
  # npm (Own & Template Frontend/Infrastructure)
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "template/*/frontend/"
      - "template/*/infrastructure/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      minor-patch-typescript-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  # Template's Backend
  - package-ecosystem: "cargo"
    directories:
      - "template/*/backend/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      minor-patch-rust-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch"]
